// Mehmon fuqaroligi uchun ro'yxat. Birinchi bo'lib O'zbekiston va qo'shni/eng
// ko'p uchraydigan davlatlar, so'ng qolganlari alifbo tartibida.
export const DEFAULT_NATIONALITY = "O'zbekiston";

export const NATIONALITIES: string[] = [
  "O'zbekiston",
  "Qozog'iston",
  "Qirg'iziston",
  "Tojikiston",
  "Turkmaniston",
  "Rossiya",
  "Afg'oniston",
  "Ozarbayjon",
  "Armaniston",
  "Belarus",
  "Gruziya",
  "Turkiya",
  "Xitoy",
  "Hindiston",
  "Pokiston",
  "Eron",
  "Janubiy Koreya",
  "Yaponiya",
  "Malayziya",
  "Indoneziya",
  "BAA",
  "Saudiya Arabistoni",
  "Misr",
  "Isroil",
  "AQSH",
  "Kanada",
  "Buyuk Britaniya",
  "Germaniya",
  "Fransiya",
  "Italiya",
  "Ispaniya",
  "Niderlandiya",
  "Belgiya",
  "Shveytsariya",
  "Avstriya",
  "Polsha",
  "Chexiya",
  "Ukraina",
  "Moldova",
  "Litva",
  "Latviya",
  "Estoniya",
  "Shvetsiya",
  "Norvegiya",
  "Finlyandiya",
  "Daniya",
  "Avstraliya",
  "Braziliya",
  "Boshqa",
];
